-- Set up script for the Hello Snowflake! application.
CREATE APPLICATION ROLE IF NOT EXISTS APP_PUBLIC;
CREATE SCHEMA IF NOT EXISTS CORE;
GRANT USAGE ON SCHEMA CORE TO APPLICATION ROLE APP_PUBLIC;

CREATE SCHEMA IF NOT EXISTS TASKS;
GRANT USAGE ON SCHEMA TASKS TO APPLICATION ROLE APP_PUBLIC;


-- 2nd Part
CREATE OR ALTER VERSIONED SCHEMA CRM;
GRANT USAGE ON SCHEMA CRM TO APPLICATION ROLE APP_PUBLIC;

CREATE OR ALTER VERSIONED SCHEMA PYTHON_FUNCTIONS;
GRANT USAGE ON SCHEMA PYTHON_FUNCTIONS TO APPLICATION ROLE APP_PUBLIC;

CREATE OR REPLACE STREAMLIT CORE.SNOWFLAKE_FOR_C360_MARKETING_APP
  FROM '/streamlit'
  MAIN_FILE = '/Home.py'
;

GRANT USAGE ON STREAMLIT CORE.SNOWFLAKE_FOR_C360_MARKETING_APP TO APPLICATION ROLE APP_PUBLIC;

CREATE OR REPLACE SECURE VIEW CRM.C360_CLICKS_CRM_JOINED_VW AS SELECT * FROM SHARED_CONTENT.C360_CLICKS_CRM_JOINED_VW;
GRANT SELECT ON VIEW CRM.C360_CLICKS_CRM_JOINED_VW TO APPLICATION ROLE APP_PUBLIC;

CREATE OR REPLACE SECURE VIEW CRM.CAMPAIGN72_VIEW AS SELECT * FROM SHARED_CONTENT.CAMPAIGN72_VIEW;
GRANT SELECT ON VIEW CRM.CAMPAIGN72_VIEW TO APPLICATION ROLE APP_PUBLIC;
